# Generated by Django 4.2.4 on 2023-08-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(upload_to='index\\static\\img'),
        ),
    ]
