# Generated by Django 4.2.4 on 2023-08-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_amount',
            field=models.FloatField(),
        ),
    ]
